sudo: false
language: node_js
cache:
  yarn: true
  directories:
  - node_modules
  - "$HOME/.npm"
  - "$HOME/.nvm"
notifications:
  email: false
node_js:
  - 8.12.0

script:
  - yarn run test:coverage

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

branches:
  only:
    - master
